# Integration tests CodeBuild
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd integration-tests
      - npm install
  build:
    commands:
      - bash ./codebuild-run-tests.sh
artifacts:
  files:
    - integration-tests/**/*
